/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { OAuthService } from "../oAuth.service";
import { OAuthCreateInput } from "./OAuthCreateInput";
import { OAuth } from "./OAuth";
import { OAuthFindManyArgs } from "./OAuthFindManyArgs";
import { OAuthWhereUniqueInput } from "./OAuthWhereUniqueInput";
import { OAuthUpdateInput } from "./OAuthUpdateInput";

export class OAuthControllerBase {
  constructor(protected readonly service: OAuthService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: OAuth })
  async createOAuth(@common.Body() data: OAuthCreateInput): Promise<OAuth> {
    return await this.service.createOAuth({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        provider: true,
        token: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [OAuth] })
  @ApiNestedQuery(OAuthFindManyArgs)
  async oAuths(@common.Req() request: Request): Promise<OAuth[]> {
    const args = plainToClass(OAuthFindManyArgs, request.query);
    return this.service.oAuths({
      ...args,
      select: {
        createdAt: true,
        id: true,
        provider: true,
        token: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: OAuth })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async oAuth(
    @common.Param() params: OAuthWhereUniqueInput
  ): Promise<OAuth | null> {
    const result = await this.service.oAuth({
      where: params,
      select: {
        createdAt: true,
        id: true,
        provider: true,
        token: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: OAuth })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOAuth(
    @common.Param() params: OAuthWhereUniqueInput,
    @common.Body() data: OAuthUpdateInput
  ): Promise<OAuth | null> {
    try {
      return await this.service.updateOAuth({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          provider: true,
          token: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: OAuth })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOAuth(
    @common.Param() params: OAuthWhereUniqueInput
  ): Promise<OAuth | null> {
    try {
      return await this.service.deleteOAuth({
        where: params,
        select: {
          createdAt: true,
          id: true,
          provider: true,
          token: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
