/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { OAuth } from "./OAuth";
import { OAuthCountArgs } from "./OAuthCountArgs";
import { OAuthFindManyArgs } from "./OAuthFindManyArgs";
import { OAuthFindUniqueArgs } from "./OAuthFindUniqueArgs";
import { CreateOAuthArgs } from "./CreateOAuthArgs";
import { UpdateOAuthArgs } from "./UpdateOAuthArgs";
import { DeleteOAuthArgs } from "./DeleteOAuthArgs";
import { User } from "../../user/base/User";
import { OAuthService } from "../oAuth.service";
@graphql.Resolver(() => OAuth)
export class OAuthResolverBase {
  constructor(protected readonly service: OAuthService) {}

  async _oAuthsMeta(
    @graphql.Args() args: OAuthCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [OAuth])
  async oAuths(@graphql.Args() args: OAuthFindManyArgs): Promise<OAuth[]> {
    return this.service.oAuths(args);
  }

  @graphql.Query(() => OAuth, { nullable: true })
  async oAuth(
    @graphql.Args() args: OAuthFindUniqueArgs
  ): Promise<OAuth | null> {
    const result = await this.service.oAuth(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => OAuth)
  async createOAuth(@graphql.Args() args: CreateOAuthArgs): Promise<OAuth> {
    return await this.service.createOAuth({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => OAuth)
  async updateOAuth(
    @graphql.Args() args: UpdateOAuthArgs
  ): Promise<OAuth | null> {
    try {
      return await this.service.updateOAuth({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => OAuth)
  async deleteOAuth(
    @graphql.Args() args: DeleteOAuthArgs
  ): Promise<OAuth | null> {
    try {
      return await this.service.deleteOAuth(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: OAuth): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
